const Arrobj = [
    {
      id:1,
      title: "Node JS Tutorial",
      src: "https://source.unsplash.com/random/200x100",
      views: "80K",
      time: "9 hrs ago",
      channel: "CodeWithMike",
      logo: "https://source.unsplash.com/random/200x100",
      verified: false,
    },
    {
      id:2,
      title: "HTML Tutorial",
      src: "https://source.unsplash.com/random/300x200",
      views: "80K",
      time: "9 hrs ago",
      channel: "Mr. Beast",
      logo: "https://source.unsplash.com/random/300x200",
      verified: true,
    },
    {
      id:3,
      title: "HTML Tutorial",
      src: "https://source.unsplash.com/random/300x120",
      views: "80K",
      time: "9 hrs ago",
      channel: "My Kitchen",
      logo: "https://source.unsplash.com/random/300x120",
      verified: true,
    },
    {
      id:4,
      title: "HTML Tutorial",
      src: "https://source.unsplash.com/random/300x150",
      views: "80K",
      time: "9 hrs ago",
      channel: "Carryminati",
      logo: "https://source.unsplash.com/random/300x150",
      verified: false,
    },
    {
      id:5,
      title: "HTML Tutorial",
      src: "https://source.unsplash.com/random/100x100",
      views: "80K",
      time: "9 hrs ago",
      channel: "Gate Smasher",
      logo: "https://source.unsplash.com/random/100x100",
      verified: true,
    },
    {
      id:6,
      title: "(DAA)Design and Analysis Of Algorithm",
      src: "https://source.unsplash.com/random/300x100",
      views: "80K",
      time: "9 hrs ago",
      channel: "Anand Singh Jalal",
      logo: "https://source.unsplash.com/random/300x100",
      verified: true,
    },
  ];
  export default Arrobj;